const stocks = [0, 8, 12, 20, 40, 55, 65, 42];

export const data = [
  {
    id: 1,
    title: "Ancient Market",
    description:
      "Painting of a market set in ancient times with ancient buildings and people buying goods.",
    price: 1500,
    trending: true,
    discount: 10,
    rating: {
      star: 4.8,
      count: 35,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Sophie Johnson",
    category: ["ancient", "street"],
    thumbnail: "canvas-1",
    images: ["canvas-1"],
  },
  {
    id: 2,
    title: "Beautiful Scenery",
    description:
      "Painting of a beautiful scenery with blossom on tree. Behind there is a mountain. Sky is reddish.",
    price: 2000,
    trending: true,
    discount: 5,
    rating: {
      star: 4.5,
      count: 30,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Ethan Smith",
    category: ["scenery"],
    thumbnail: "canvas-2",
    images: ["canvas-2"],
  },
  {
    id: 3,
    title: "Futuristic Cityscape",
    description:
      "A futuristic cityscape with sleek skyscrapers, bustling streets, and flying cars zooming overhead.",
    price: 1200,
    discount: 10,
    rating: {
      star: 3.5,
      count: 53,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Liam Martinez",
    category: ["cityscape", "futuristic"],
    thumbnail: "cityscape-1",
    images: ["cityscape-1"],
  },
  {
    id: 4,
    title: "Futuristic Cityscape",
    description:
      "Painting of futuristic cityscape with sleek skyscrapers, and cars on road.",
    price: 1500,
    discount: 10,
    rating: {
      star: 4.5,
      count: 120,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Liam Martinez",
    category: ["cityscape", "futuristic"],
    thumbnail: "cityscape-2",
    images: ["cityscape-2"],
  },
  {
    id: 5,
    title: "Countryside",
    description:
      "a peaceful countryside setting with rolling hills, picturesque farms, and quaint cottages nestled among the fields.",
    price: 2000,
    discount: 5,
    rating: {
      star: 4,
      count: 32,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Benjamin Clark",
    category: ["countryside"],
    thumbnail: "countryside-1",
    images: ["countryside-1", "countryside-2", "countryside-3"],
  },
  {
    id: 6,
    title: "Countryside",
    description:
      "a peaceful countryside setting with rolling hills, picturesque farms, and quaint cottages nestled among the fields.",
    price: 2500,
    discount: 10,
    rating: {
      star: 3.3,
      count: 59,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Benjamin Clark",
    category: ["countryside"],
    thumbnail: "countryside-2",
    images: ["countryside-1", "countryside-2", "countryside-3"],
  },
  {
    id: 7,
    title: "Countryside",
    description:
      "a peaceful countryside setting with rolling hills, picturesque farms, and quaint cottages nestled among the fields.",
    price: 2800,
    discount: 10,
    rating: {
      star: 2.3,
      count: 35,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Benjamin Clark",
    category: ["countryside"],
    thumbnail: "countryside-3",
    images: [
      "countryside-1",
      "countryside-2",
      "countryside-3",
      "countryside-4",
    ],
  },
  {
    id: 8,
    title: "Underwater World",
    description:
      "An enchanting underwater world teeming with colorful coral reefs, exotic fish, and mysterious sea creatures.",
    price: 2500,
    discount: 5,
    rating: {
      star: 3.8,
      count: 68,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "James Wright",
    category: ["underwater"],
    thumbnail: "fish-underwater-1",
    images: ["fish-underwater-1", "fish-underwater-2", "fish-underwater-3"],
  },
  {
    id: 9,
    title: "Magical Forest",
    description:
      "A whimsical scene of a magical forest inhabited by mythical creatures like unicorns, fairies, and talking animals.",
    price: 2500,
    discount: 10,
    rating: {
      star: 4.5,
      count: 95,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Evelyn Rivera",
    category: ["forest"],
    thumbnail: "forest-1",
    images: ["forest-1"],
  },
  {
    id: 10,
    title: "Magical Forest",
    description:
      "A whimsical scene of a magical forest inhabited by mythical creatures like unicorns, fairies, and talking animals.",
    price: 2500,
    discount: 10,
    rating: {
      star: 4.5,
      count: 95,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Evelyn Rivera",
    category: ["forest"],
    thumbnail: "forest-2",
    images: ["forest-2", "forest-3", "forest-4"],
  },
  {
    id: 11,
    title: "Magical Forest",
    description:
      "A whimsical scene of a magical forest inhabited by mythical creatures like unicorns, fairies, and talking animals.",
    price: 2500,
    featured: true,
    discount: 10,
    rating: {
      star: 4.5,
      count: 95,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Evelyn Rivera",
    category: ["forest"],
    thumbnail: "forest-3",
    images: ["forest-1", "forest-2", "forest-3"],
  },
  {
    id: 12,
    title: "Magical Forest",
    description:
      "A whimsical scene of a magical forest inhabited by mythical creatures like unicorns, fairies, and talking animals.",
    price: 2500,
    discount: 10,
    rating: {
      star: 4.5,
      count: 95,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Evelyn Rivera",
    category: ["forest"],
    thumbnail: "forest-4",
    images: ["forest-3", "forest-4", "forest-5"],
  },
  {
    id: 13,
    title: "Indian Street",
    description:
      "Potrait of ancient Indian street. People of ancient India. Ancient buildings and marketplace.",
    price: 2500,
    featured: true,
    discount: 10,
    rating: {
      star: 5,
      count: 350,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Ramesh Raj",
    category: ["ancient", "street", "india"],
    thumbnail: "indian-street-1",
    images: ["indian-street-1", "indian-street-2", "indian-street-3"],
  },
  {
    id: 14,
    title: "Indian Street",
    description:
      "Potrait of ancient Indian street. People of ancient India. Ancient buildings and marketplace.",
    price: 2500,
    discount: 10,
    rating: {
      star: 5,
      count: 350,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Ramesh Raj",
    category: ["ancient", "street", "india"],
    thumbnail: "indian-street-2",
    images: ["indian-street-1", "indian-street-2", "indian-street-3"],
  },
  {
    id: 15,
    title: "Indian Street",
    description:
      "Potrait of ancient Indian street. People of ancient India. Ancient buildings and marketplace.",
    price: 2500,
    discount: 10,
    rating: {
      star: 5,
      count: 350,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Ramesh Raj",
    category: ["ancient", "street", "india"],
    thumbnail: "indian-street-4",
    images: ["indian-street-1", "indian-street-2", "indian-street-3"],
  },
  {
    id: 16,
    title: "Indian Street",
    description:
      "Potrait of ancient Indian street. People of ancient India. Ancient buildings and marketplace.",
    price: 2500,
    discount: 10,
    rating: {
      star: 5,
      count: 350,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Ramesh Raj",
    category: ["ancient", "street", "india"],
    thumbnail: "indian-street-5",
    images: ["indian-street-5", "indian-street-2", "indian-street-3"],
  },
  {
    id: 17,
    title: "Mysterious Plant",
    description: "Painting of a mysterious plant.",
    price: 1000,
    discount: 10,
    rating: {
      star: 5,
      count: 350,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Mark Wood",
    category: ["plant", "scenery"],
    thumbnail: "plant-painting",
    images: ["plant-painting"],
  },
  {
    id: 18,
    title: "Street Sketch",
    description: "Sketch of a street.",
    trending: true,
    price: 1500,
    discount: 5,
    rating: {
      star: 5,
      count: 96,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Da Li John",
    category: ["sketch"],
    thumbnail: "sketch",
    images: ["sketch"],
  },
  {
    id: 19,
    title: "Street Potrait",
    description: "Painting of a street.",
    price: 2200,
    featured: true,
    discount: 10,
    rating: {
      star: 4.5,
      count: 50,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["street"],
    thumbnail: "street-1",
    images: ["street-1", "street-2", "street-3"],
  },
  {
    id: 20,
    title: "Street Potrait",
    description: "Painting of a street.",
    trending: true,
    price: 2200,
    discount: 10,
    rating: {
      star: 4.5,
      count: 50,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["street"],
    thumbnail: "street-2",
    images: ["street-1", "street-2", "street-3", "street-painting"],
  },
  {
    id: 21,
    title: "Street Potrait",
    description: "Painting of a street.",
    price: 2200,
    discount: 10,
    rating: {
      star: 2.5,
      count: 20,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["street"],
    thumbnail: "street-3",
    images: ["street-1", "street-2", "street-3", "street-painting"],
  },
  {
    id: 22,
    title: "Street Potrait",
    description: "Painting of a street.",
    price: 2200,
    discount: 10,
    rating: {
      star: 4.5,
      count: 50,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["street"],
    thumbnail: "street-4",
    images: ["street-1", "street-2", "street-4", "street-painting"],
  },
  {
    id: 23,
    title: "Street Potrait",
    description: "Painting of a street.",
    price: 2200,
    discount: 10,
    rating: {
      star: 4.5,
      count: 50,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["street"],
    thumbnail: "street-5",
    images: ["street-1", "street-2", "street-5", "street-painting"],
  },
  {
    id: 24,
    title: "Turtle Underwater",
    description: "Portrait of a turtle underwater.",
    price: 2500,
    featured: true,
    discount: 10,
    rating: {
      star: 5,
      count: 70,
    },
    stock: stocks[Math.floor(Math.random() * stocks.length)],
    artist: "Raman Dhuv",
    category: ["underwater"],
    thumbnail: "turtle-underwater-1",
    images: [
      "turtle-underwater-1",
      "turtle-underwater-2",
      "turtle-underwater-3",
    ],
  },
];
